version: '3'

services:
  db:
    image: postgres:latest
    container_name: my_postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: practica2b_grupo5
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: flask_app_practica2b_grupo5
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db/practica2b_grupo5