db:
  image: mongo:3.2
  expose:
    - 27017
web:
  build: .
  command: gunicorn -b 0.0.0.0:8000 manage:app
  volumes:
    - .:/code
  expose:
    - 8000
  ports:
    - "8000:8000"
  links:
    - db
  environment:
    - HOST=0.0.0.0
    - PORT=8000
    - DATABASE_HOST=db

